conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: ffhq
  root: ./data/samples/

measurement:
  operator:
    name: diffuser_cam
    psf_path: ./data/psf_sample.jpg
  
  noise: 
    name: gaussian
    sigma: 0.05