conditioning:
  method: ps
  params:
    scale: 0.3
  deconv_init: False

data:
  name: ffhq
  root: ./data/samples/

measurement:
  operator:
    name: shuffle
    shifts: [100,50]
  
  noise: 
    name: gaussian
    sigma: 0.05